apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: verify-company-website
spec:
  mode: enforce
  images:
  - glob: ghcr.io/jonity-itsx/company-website**
  authorities:
  - name: deploy-workflow
    keyless:
      identities:
      - issuer: https://token.actions.githubusercontent.com
        subjectRegExp: ^https://github\.com/jonity-itsx/company-website/\.github/workflows/deploy\.yml@.*$
